[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>", "Nikita Pekin <contact@nikitapek.in>"]
description = "AWS SDK for Rust - Amazon Elastic Compute Cloud @ 2016-11-15"
documentation = "https://docs.rs/rusoto_ec2"
keywords = ["AWS", "Amazon", "ec2"]
license = "MIT"
name = "rusoto_ec2"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.43.0-beta1"
homepage = "https://www.rusoto.org/"
edition = "2018"
exclude = ["test_resources/*"]

[build-dependencies]

[dependencies]
async-trait = "0.1"
bytes = "0.5"
serde_urlencoded = "0.6"
xml-rs = "0.8"

[dependencies.futures]
version = "0.3"

[dependencies.rusoto_core]
version = "0.43.0-beta1"
path = "../../core"
default-features = false

[dependencies.serde]
version = "1.0.2"
optional = true

[dependencies.serde_derive]
version = "1.0.2"
optional = true

[dev-dependencies]
tokio = "0.2"

[dev-dependencies.rusoto_mock]
version = "0.43.0-beta1"
path = "../../../mock"
default-features = false

[features]
default = ["native-tls"]
deserialize_structs = ["bytes/serde"]
native-tls = ["rusoto_core/native-tls"]
rustls = ["rusoto_core/rustls"]
serialize_structs = ["bytes/serde"]
