[package]
name = "skeptical"
version = "0.1.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]
build = "build.rs"

[dependencies]
rusoto_core = "0.38"
rusoto_dynamodb = "0.38"
rusoto_s3 = "0.38"
rusoto_ec2 = "0.38"
rusoto_sts = "0.38"
env_logger = "0.5"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13" 