[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
description = "AWS SDK for Rust - Request Mocking Helpers"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto_mock"
repository = "https://github.com/rusoto/rusoto"
version = "0.28.0"
homepage = "https://www.rusoto.org/"

[dependencies]
chrono = "0.4.0"
futures = "0.1.16"
http = "0.1.7"
serde = "1.0.2"
serde_json = "1.0.2"
[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.rusoto_core]
version = "> 0.25.0"
path = "../rusoto/core"
default_features = false

[features]
nightly-testing = ["clippy", "rusoto_core/nightly-testing"]
unstable = []
