trigger: ["master"]
pr: ["master"]

jobs:
- job: 'unit_and_integration_tests_linux'
  displayName: 'Unit and integration tests on Linux'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: rustc --version
      displayName: 'print rust version'
    - script: make unit_test
      displayName: 'Run unit tests'
    - script: make check_integration_test
      displayName: 'Cargo check integration tests'
    - script: make credential_integration_test
      displayName: 'Credential integration tests'

- job: 'rustls_unit_tests_linux'
  displayName: 'Rustls unit tests on Linux'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: rustc --version
      displayName: 'print rust version'
    - script: make rustls_unit_test
      displayName: 'Run unit tests with rustls'

- job: 'unit_and_integration_tests_linux_beta'
  displayName: 'Unit and integration tests on Linux (beta channel)'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain beta-x86_64-unknown-linux-gnu -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rustup'
    - script: |
        rustup install beta
        rustup default beta
      displayName: 'Install Rust beta'
    - script: RUST_VERSION=beta make unit_test
      displayName: 'Run unit tests'

- job: 'rustls_unit_tests_linux_beta'
  displayName: 'Rustls unit tests on Linux (beta channel)'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain beta-x86_64-unknown-linux-gnu -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rustup'
    - script: |
        rustup install beta
        rustup default beta
      displayName: 'Install Rust beta'
    - script: RUST_VERSION=beta make rustls_unit_test
      displayName: 'Run unit tests with rustls'

- job: 'unit_and_integration_tests_linux_nightly'
  displayName: 'Unit and integration tests on Linux (nightly channel)'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-x86_64-unknown-linux-gnu -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rustup'
    - script: |
        rustup install nightly
        rustup default nightly
      displayName: 'Install Rust nightly'
    - script: RUST_VERSION=nightly make unit_test_no_doctests
      displayName: 'Run unit tests'
      continueOnError: true
    - script: RUST_VERSION=nightly make check_integration_test
      displayName: 'Cargo check integration tests'
      continueOnError: true

- job: 'rustls_unit_tests_linux_nightly'
  displayName: 'Rustls unit tests on Linux (nightly channel)'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-x86_64-unknown-linux-gnu -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rustup'
    - script: |
        rustup install nightly
        rustup default nightly
      displayName: 'Install Rust nightly'
    - script:  RUST_VERSION=nightly make rustls_unit_test_no_doctests
      displayName: 'Run unit tests with rustls'
      continueOnError: true

- job: 'unit_and_integration_tests_osx'
  displayName: 'Unit and integration tests on OSX'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: make unit_test
      displayName: 'Run unit tests'
    - script: make check_integration_test
      displayName: 'Cargo check integration tests'

- job: 'rustls_unit_tests_osx'
  displayName: 'Unit and integration tests on OSX'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: make rustls_unit_test
      displayName: 'Run unit tests with rustls'

- job: 'unit_and_integration_tests_osx_beta'
  displayName: 'Unit and integration tests on OSX (beta channel)'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: RUST_VERSION=beta make unit_test
      displayName: 'Run unit tests'
    - script: RUST_VERSION=beta make check_integration_test
      displayName: 'Cargo check integration tests'

- job: 'rustls_unit_tests_osx_beta'
  displayName: 'Rustls unit tests on OSX (beta channel)'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: RUST_VERSION=beta make rustls_unit_test
      displayName: 'Run unit tests with rustls'

- job: 'unit_and_integration_tests_osx_nightly'
  displayName: 'Unit and integration tests on OSX (nightly channel)'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: RUST_VERSION=nightly make unit_test_no_doctests
      displayName: 'Run unit tests'
      continueOnError: true
    - script: RUST_VERSION=nightly make check_integration_test
      displayName: 'Cargo check integration tests'
      continueOnError: true

- job: 'rustls_unit_tests_osx_nightly'
  displayName: 'Rustls unit tests on OSX (nightly channel)'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: RUST_VERSION=nightly make rustls_unit_test_no_doctests
      displayName: 'Run unit tests with rustls'
      continueOnError: true

- job: 'crate_gen_osx'
  displayName: 'Crate generation on OSX'
  pool:
    vmImage: 'macos-10.13'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: rustup component add --toolchain stable rustfmt
      displayName: 'Install rustfmt'
    - script: git submodule update --init --recursive
      displayName: 'Fetch botocore sources'
    - script: make generate
      displayName: 'Generate crates from botocore'

- job: 'crate_gen_windows'
  displayName: 'Crate generation on Windows'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain stable
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
      displayName: 'Install Rust'
    - script: rustup component add --toolchain stable rustfmt
      displayName: 'Install rustfmt'
    - script: git submodule update --init --recursive
      displayName: 'Fetch botocore sources'
    - script: make generate
      displayName: 'Generate crates from botocore'

- job: 'skeptic_linux'
  displayName: 'Skeptic tests on Linux'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 5
    - script: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: 'Install Rust'
    - script: make skeptical
      displayName: 'Run skeptic tests'
