[package]
name = "rusoto"
version = "0.2.0"
authors = ["Anthony DiMarco <anthony.dimarco@dualspark.com>", "Matthew Mayer <matthew@dualspark.com>"]
license = "MIT"
readme = "README.md"
keywords = [ "AWS", "SQS", "Amazon" ]
description = "AWS client libraries for Rust"
repository = "https://github.com/DualSpark/rust-aws"

[dependencies]
xml-rs = "*"
time = "*"
openssl = "*"
hyper = "0.6.1"
url = "*"
rustc-serialize = "*"
regex = "0.1.41"
chrono = "*"
