[workspace]
members = [
    "rusoto/core",
    "rusoto/credential",
    "rusoto/services/acm",
    "rusoto/services/apigateway",
    "rusoto/services/application-autoscaling",
    "rusoto/services/appstream",
    "rusoto/services/autoscaling",
    "rusoto/services/batch",
    "rusoto/services/cloudformation",
    "rusoto/services/cloudfront",
    "rusoto/services/cloudhsm",
    "rusoto/services/cloudsearch",
    "rusoto/services/cloudsearchdomain",
    "rusoto/services/cloudtrail",
    "rusoto/services/cloudwatch",
    "rusoto/services/codebuild",
    "rusoto/services/codecommit",
    "rusoto/services/codedeploy",
    "rusoto/services/codepipeline",
    "rusoto/services/cognito-identity",
    "rusoto/services/cognito-idp",
    "rusoto/services/config",
    "rusoto/services/cur",
    "rusoto/services/datapipeline",
    "rusoto/services/devicefarm",
    "rusoto/services/directconnect",
    "rusoto/services/dms",
    "rusoto/services/ds",
    "rusoto/services/dynamodb",
    "rusoto/services/dynamodbstreams",
    "rusoto/services/ec2",
    "rusoto/services/ecr",
    "rusoto/services/ecs",
    "rusoto/services/elasticache",
    "rusoto/services/elasticbeanstalk",
    "rusoto/services/efs",
    "rusoto/services/elastictranscoder",
    "rusoto/services/elb",
    "rusoto/services/elbv2",
    "rusoto/services/emr",
    "rusoto/services/events",
    "rusoto/services/firehose",
    "rusoto/services/gamelift",
    "rusoto/services/glacier",
    "rusoto/services/greengrass",
    "rusoto/services/health",
    "rusoto/services/iam",
    "rusoto/services/importexport",
    "rusoto/services/inspector",
    "rusoto/services/iot",
    "rusoto/services/kinesis",
    "rusoto/services/kinesisanalytics",
    "rusoto/services/kms",
    "rusoto/services/lambda",
    "rusoto/services/lightsail",
    "rusoto/services/logs",
    "rusoto/services/machinelearning",
    "rusoto/services/marketplacecommerceanalytics",
    "rusoto/services/meteringmarketplace",
    "rusoto/services/mturk",
    "rusoto/services/opsworks",
    "rusoto/services/opsworkscm",
    "rusoto/services/organizations",
    "rusoto/services/polly",
    "rusoto/services/rds",
    "rusoto/services/redshift",
    "rusoto/services/rekognition",
    "rusoto/services/route53",
    "rusoto/services/route53domains",
    "rusoto/services/s3",
    "rusoto/services/sdb",
    "rusoto/services/servicecatalog",
    "rusoto/services/ses",
    "rusoto/services/sms",
    "rusoto/services/snowball",
    "rusoto/services/sns",
    "rusoto/services/sqs",
    "rusoto/services/ssm",
    "rusoto/services/stepfunctions",
    "rusoto/services/storagegateway",
    "rusoto/services/sts",
    "rusoto/services/support",
    "rusoto/services/swf",
    "rusoto/services/waf",
    "rusoto/services/waf-regional",
    "rusoto/services/workspaces",
    "rusoto/services/xray"
]

exclude = [
    "helpers",
    "integration_tests",
    "mock",
    "service_crategen",
]