[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
description = "AWS SDK for Rust"
documentation = "https://rusoto.github.io/rusoto/rusoto_core/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh", "helpers/**/*", "codegen/**/*"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.25.0"
homepage = "https://www.rusoto.org/"

[badges]
travis-ci = { repository = "rusoto/rusoto", branch = "master" }
appveyor = { repository = "rusoto/rusoto", branch = "master" }

[dependencies.rusoto_core]
path = "rusoto/core"
version = "0.25.0"

[dependencies.rusoto_acm]
optional = true
path = "rusoto/services/acm"
version = "0.25.0"

[dependencies.rusoto_autoscaling]
optional = true
path = "rusoto/services/autoscaling"
version = "0.25.0"

[dependencies.rusoto_cloudformation]
optional = true
path = "rusoto/services/cloudformation"
version = "0.25.0"

[dependencies.rusoto_cloudfront]
optional = true
path = "rusoto/services/cloudfront"
version = "0.25.0"

[dependencies.rusoto_cloudhsm]
optional = true
path = "rusoto/services/cloudhsm"
version = "0.25.0"

[dependencies.rusoto_cloudsearch]
optional = true
path = "rusoto/services/cloudsearch"
version = "0.25.0"

[dependencies.rusoto_cloudtrail]
optional = true
path = "rusoto/services/cloudtrail"
version = "0.25.0"

[dependencies.rusoto_cloudwatch]
optional = true
path = "rusoto/services/cloudwatch"
version = "0.25.0"

[dependencies.rusoto_codecommit]
optional = true
path = "rusoto/services/codecommit"
version = "0.25.0"

[dependencies.rusoto_codedeploy]
optional = true
path = "rusoto/services/codedeploy"
version = "0.25.0"

[dependencies.rusoto_codepipeline]
optional = true
path = "rusoto/services/codepipeline"
version = "0.25.0"

[dependencies.rusoto_cognito_identity]
optional = true
path = "rusoto/services/cognito-identity"
version = "0.25.0"

[dependencies.rusoto_config]
optional = true
path = "rusoto/services/config"
version = "0.25.0"

[dependencies.rusoto_datapipeline]
optional = true
path = "rusoto/services/datapipeline"
version = "0.25.0"

[dependencies.rusoto_devicefarm]
optional = true
path = "rusoto/services/devicefarm"
version = "0.25.0"

[dependencies.rusoto_directconnect]
optional = true
path = "rusoto/services/directconnect"
version = "0.25.0"

[dependencies.rusoto_ds]
optional = true
path = "rusoto/services/ds"
version = "0.25.0"

[dependencies.rusoto_dynamodb]
optional = true
path = "rusoto/services/dynamodb"
version = "0.25.0"

[dependencies.rusoto_dynamodbstreams]
optional = true
path = "rusoto/services/dynamodbstreams"
version = "0.25.0"

[dependencies.rusoto_ec2]
optional = true
path = "rusoto/services/ec2"
version = "0.25.0"

[dependencies.rusoto_ecr]
optional = true
path = "rusoto/services/ecr"
version = "0.25.0"

[dependencies.rusoto_ecs]
optional = true
path = "rusoto/services/ecs"
version = "0.25.0"

[dependencies.rusoto_elasticache]
optional = true
path = "rusoto/services/elasticache"
version = "0.25.0"

[dependencies.rusoto_elasticbeanstalk]
optional = true
path = "rusoto/services/elasticbeanstalk"
version = "0.25.0"

[dependencies.rusoto_elastictranscoder]
optional = true
path = "rusoto/services/elastictranscoder"
version = "0.25.0"

[dependencies.rusoto_elb]
optional = true
path = "rusoto/services/elb"
version = "0.25.0"

[dependencies.rusoto_elbv2]
optional = true
path = "rusoto/services/elbv2"
version = "0.25.0"

[dependencies.rusoto_emr]
optional = true
path = "rusoto/services/emr"
version = "0.25.0"

[dependencies.rusoto_events]
optional = true
path = "rusoto/services/events"
version = "0.25.0"

[dependencies.rusoto_firehose]
optional = true
path = "rusoto/services/firehose"
version = "0.25.0"

[dependencies.rusoto_iam]
optional = true
path = "rusoto/services/iam"
version = "0.25.0"

[dependencies.rusoto_importexport]
optional = true
path = "rusoto/services/importexport"
version = "0.25.0"

[dependencies.rusoto_inspector]
optional = true
path = "rusoto/services/inspector"
version = "0.25.0"

[dependencies.rusoto_iot]
optional = true
path = "rusoto/services/iot"
version = "0.25.0"

[dependencies.rusoto_kinesis]
optional = true
path = "rusoto/services/kinesis"
version = "0.25.0"

[dependencies.rusoto_kms]
optional = true
path = "rusoto/services/kms"
version = "0.25.0"

[dependencies.rusoto_lambda]
optional = true
path = "rusoto/services/lambda"
version = "0.25.0"

[dependencies.rusoto_logs]
optional = true
path = "rusoto/services/logs"
version = "0.25.0"

[dependencies.rusoto_machinelearning]
optional = true
path = "rusoto/services/machinelearning"
version = "0.25.0"

[dependencies.rusoto_marketplacecommerceanalytics]
optional = true
path = "rusoto/services/marketplacecommerceanalytics"
version = "0.25.0"

[dependencies.rusoto_opsworks]
optional = true
path = "rusoto/services/opsworks"
version = "0.25.0"

[dependencies.rusoto_redshift]
optional = true
path = "rusoto/services/redshift"
version = "0.25.0"

[dependencies.rusoto_rds]
optional = true
path = "rusoto/services/rds"
version = "0.25.0"

[dependencies.rusoto_route53]
optional = true
path = "rusoto/services/route53"
version = "0.25.0"

[dependencies.rusoto_route53domains]
optional = true
path = "rusoto/services/route53domains"
version = "0.25.0"

[dependencies.rusoto_s3]
optional = true
path = "rusoto/services/s3"
version = "0.25.0"

[dependencies.rusoto_sdb]
optional = true
path = "rusoto/services/sdb"
version = "0.25.0"

[dependencies.rusoto_ses]
optional = true
path = "rusoto/services/ses"
version = "0.25.0"

[dependencies.rusoto_sns]
optional = true
path = "rusoto/services/sns"
version = "0.25.0"

[dependencies.rusoto_sqs]
optional = true
path = "rusoto/services/sqs"
version = "0.25.0"

[dependencies.rusoto_ssm]
optional = true
path = "rusoto/services/ssm"
version = "0.25.0"

[dependencies.rusoto_storagegateway]
optional = true
path = "rusoto/services/storagegateway"
version = "0.25.0"

[dependencies.rusoto_sts]
optional = true
path = "rusoto/services/sts"
version = "0.25.0"

[dependencies.rusoto_swf]
optional = true
path = "rusoto/services/swf"
version = "0.25.0"

[dependencies.rusoto_waf]
optional = true
path = "rusoto/services/waf"
version = "0.25.0"

[dependencies.rusoto_workspaces]
optional = true
path = "rusoto/services/workspaces"
version = "0.25.0"

[dev-dependencies]
env_logger = "0.4.0"
hyper = "0.10.0"
log = "0.3.6"
rand = "^0.3.14"
time = "0.1.37"

[features]
all = [
		"acm",
	   	"autoscaling",
	   	"cloudformation",
	   	"cloudfront",
	   	"cloudhsm",
	   	"cloudsearch",
	   	"cloudtrail",
	   	"cloudwatch",
	   	"codecommit",
	   	"codedeploy",
	   	"codepipeline",
	   	"cognito-identity",
	   	"config",
	   	"datapipeline",
	   	"devicefarm",
	   	"directconnect",
	   	"ds",
	   	"dynamodb",
	   	"dynamodbstreams",
	   	"ec2",
	   	"ecr",
	   	"ecs",
	   	"elasticache",
	   	"elasticbeanstalk",
	   	"elastictranscoder",
	   	"elb",
	   	"elbv2",
	   	"emr",
	   	"events",
	   	"firehose",
	   	"iam",
	   	"importexport",
	   	"inspector",
	   	"iot",
	   	"kinesis",
	   	"kms",
	   	"lambda",
	   	"logs",
	   	"machinelearning",
	   	"marketplacecommerceanalytics",
	   	"opsworks",
	   	"redshift",
	   	"rds",
	   	"route53",
	   	"route53domains",
	   	"s3",
	   	"sdb",
	   	"ses",
	   	"sns",
	   	"sqs",
	   	"ssm",
	   	"storagegateway",
        "sts",
	   	"swf",
	   	"waf",
	   	"workspaces"
	]
acm = ["rusoto_acm"]
autoscaling = ["rusoto_autoscaling"]
cloudformation = ["rusoto_cloudformation"]
cloudfront = ["rusoto_cloudfront"]
cloudhsm = ["rusoto_cloudhsm"]
cloudsearch = ["rusoto_cloudsearch"]
cloudtrail = ["rusoto_cloudtrail"]
cloudwatch = ["rusoto_cloudwatch"]
codecommit = ["rusoto_codecommit"]
codedeploy = ["rusoto_codedeploy"]
codepipeline = ["rusoto_codepipeline"]
cognito-identity = ["rusoto_cognito_identity"]
config = ["rusoto_config"]
datapipeline = ["rusoto_datapipeline"]
devicefarm = ["rusoto_devicefarm"]
directconnect = ["rusoto_directconnect"]
ds = ["rusoto_ds"]
dynamodb = ["rusoto_dynamodb"]
dynamodbstreams = ["rusoto_dynamodbstreams"]
ec2 = ["rusoto_ec2"]
ecr = ["rusoto_ecr"]
ecs = ["rusoto_ecs"]
elasticache = ["rusoto_elasticache"]
elasticbeanstalk = ["rusoto_elasticbeanstalk"]
elastictranscoder = ["rusoto_elastictranscoder"]
elb = ["rusoto_elb"]
elbv2 = ["rusoto_elbv2"]
emr = ["rusoto_emr"]
events = ["rusoto_events"]
firehose = ["rusoto_firehose"]
iam = ["rusoto_iam"]
importexport = ["rusoto_importexport"]
inspector = ["rusoto_inspector"]
iot = ["rusoto_iot"]
kinesis = ["rusoto_kinesis"]
kms = ["rusoto_kms"]
lambda = ["rusoto_lambda"]
logs = ["rusoto_logs"]
machinelearning = ["rusoto_machinelearning"]
marketplacecommerceanalytics = ["rusoto_marketplacecommerceanalytics"]
opsworks = ["rusoto_opsworks"]
redshift = ["rusoto_redshift"]
rds = ["rusoto_rds"]
route53 = ["rusoto_route53"]
route53domains = ["rusoto_route53domains"]
s3 = ["rusoto_s3"]
sdb = ["rusoto_sdb"]
ses = ["rusoto_ses"]
sns = ["rusoto_sns"]
sqs = ["rusoto_sqs"]
ssm = ["rusoto_ssm"]
storagegateway = ["rusoto_storagegateway"]
sts = ["rusoto_sts"]
swf = ["rusoto_swf"]
waf = ["rusoto_waf"]
workspaces = ["rusoto_workspaces"]
nightly-testing = ["rusoto_core/nightly-testing"]
packagea = [
	"acm",
	"autoscaling",
	"cloudformation",
	"cloudfront",
	"cloudhsm",
	"cloudsearch",
	"cloudtrail",
	"cloudwatch",
	"codecommit",
	"codedeploy",
	"codepipeline",
	"cognito-identity",
	"config",
	"datapipeline",
	"devicefarm",
	"directconnect",
	"ds",
	"dynamodb",
	"dynamodbstreams",
	"ec2",
	"ecr",
	"ecs",
	"elasticache",
	"elasticbeanstalk",
	"elastictranscoder",
	"elb",
	"elbv2",
	"emr",
	"events",
	"firehose"
]
packageb = [
	"iam",
	"importexport",
	"inspector",
	"iot",
	"kinesis",
	"kms",
	"lambda",
	"logs",
	"machinelearning",
	"marketplacecommerceanalytics",
	"opsworks",
	"redshift",
	"rds",
	"route53",
	"route53domains",
	"s3",
	"sdb",
	"ses",
	"sns",
	"sqs",
	"ssm",
	"storagegateway",
	"swf",
	"waf",
	"workspaces"
]