[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh", "helpers/**/*", "codegen/**/*"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.20.0"

[build-dependencies]
rustc_version = "0.1.7"

[build-dependencies.rusoto_codegen]
default-features = false
path = "codegen"
version = ">= 0.4.0"

[dependencies]
chrono = "0.2.21"
data-encoding = "1.1.2"
hyper = "0.9.10"
lazy_static = "0.2.1"
log = "0.3.6"
md5 = "0.2"
regex = "0.1.65"
ring = "0.6"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
xml-rs = "0.1.26"


[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.rusoto_credential]
path = "credential"
version = "0.2.0"

[dependencies.rusoto_signature]
path = "signature"
version = "0.1.0"

[dependencies.serde_codegen]
optional = true
version = "0.8.0"

[dependencies.serde_derive]
optional = true
version = "0.8.19"

[dev-dependencies]
env_logger = "0.3.3"
rand = "^0.3.14"
time = "0.1.35"

[features]
all = ["acm", "cloudformation", "cloudhsm", "cloudtrail", "cloudwatch", "codecommit", "codedeploy", "codepipeline", "cognito-identity", "config", "datapipeline", "devicefarm", "directconnect", "ds", "dynamodb", "dynamodbstreams", "ec2", "ecr", "ecs", "elastictranscoder", "emr", "events", "firehose", "iam", "inspector", "iot", "kinesis", "kms", "logs", "machinelearning", "marketplacecommerceanalytics", "opsworks", "route53domains", "s3", "sqs", "ssm", "storagegateway", "swf", "waf", "workspaces"]
acm = []
cloudformation = []
cloudhsm = []
cloudtrail = []
cloudwatch = []
codecommit = []
codedeploy = []
codepipeline = []
cognito-identity = []
config = []
datapipeline = []
default = ["rusoto_codegen/serde_codegen", "serde_codegen"]
devicefarm = []
directconnect = []
ds = []
dynamodb = []
dynamodbstreams = []
ec2 = []
ecr = []
ecs = []
elastictranscoder = []
emr = []
events = []
firehose = []
iam = []
inspector = []
iot = []
kinesis = []
kms = []
logs = []
machinelearning = []
marketplacecommerceanalytics = []
nightly-testing = ["clippy", "rusoto_codegen/nightly-testing", "rusoto_credential/nightly-testing", "unstable"]
opsworks = []
route53domains = []
s3 = []
sqs = []
ssm = []
storagegateway = []
swf = []
unstable = ["rusoto_codegen/unstable", "rusoto_credential/unstable", "serde_derive"]
waf = []
workspaces = []
