[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh", "helpers/**/*", "codegen/**/*"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.24.0"
homepage = "https://www.rusoto.org/"

[badges]
travis-ci = { repository = "rusoto/rusoto", branch = "master" }
appveyor = { repository = "rusoto/rusoto", branch = "master" }

[build-dependencies]
rustc_version = "0.1.7"
rayon = "0.6.0"

[build-dependencies.rusoto_codegen]
default-features = false
path = "codegen"
version = ">= 0.8.0"

[dependencies]
chrono = "0.2.21"
futures = { version = "*" }
tokio-core = { version = "*" }
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
lazy_static = "0.2.1"
log = "0.3.6"
md5 = "0.3.2"
regex = "0.2.1"
ring = "0.7"
rustc-serialize = "0.3.19"
serde = "0.9.5"
serde_derive = "0.9.5"
serde_json = "0.9.4"
time = "0.1.35"
url = "1.2.0"
xml-rs = "0.3"

[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.rusoto_credential]
path = "credential"
version = "0.6.0"

[dev-dependencies]
env_logger = "0.4.0"
rand = "^0.3.14"

[features]
all = [
		"acm",
	   	"autoscaling",
	   	"cloudformation",
	   	"cloudfront",
	   	"cloudhsm",
	   	"cloudsearch",
	   	"cloudtrail",
	   	"cloudwatch",
	   	"codecommit",
	   	"codedeploy",
	   	"codepipeline",
	   	"cognito-identity",
	   	"config",
	   	"datapipeline",
	   	"devicefarm",
	   	"directconnect",
	   	"ds",
	   	"dynamodb",
	   	"dynamodbstreams",
	   	"ec2",
	   	"ecr",
	   	"ecs",
	   	"elasticache",
	   	"elasticbeanstalk",
	   	"elastictranscoder",
	   	"elb",
	   	"elbv2",
	   	"emr",
	   	"events",
	   	"firehose",
	   	"iam",
	   	"importexport",
	   	"inspector",
	   	"iot",
	   	"kinesis",
	   	"kms",
	   	"lambda",
	   	"logs",
	   	"machinelearning",
	   	"marketplacecommerceanalytics",
	   	"opsworks",
	   	"redshift",
	   	"rds",
	   	"route53",
	   	"route53domains",
	   	"s3",
	   	"sdb",
	   	"sns",
	   	"sqs",
	   	"ssm",
	   	"storagegateway",
        "sts",
	   	"swf",
	   	"waf",
	   	"workspaces"
	]
acm = []
autoscaling = []
cloudformation = []
cloudfront = []
cloudhsm = []
cloudsearch = []
cloudtrail = []
cloudwatch = []
codecommit = []
codedeploy = []
codepipeline = []
cognito-identity = []
config = []
datapipeline = []
default = []
devicefarm = []
directconnect = []
ds = []
dynamodb = []
dynamodbstreams = []
ec2 = []
ecr = []
ecs = []
elasticache = []
elasticbeanstalk = []
elastictranscoder = []
elb = []
elbv2 = []
emr = []
events = []
firehose = []
iam = []
importexport = []
inspector = []
iot = []
kinesis = []
kms = []
lambda = []
logs = []
machinelearning = []
marketplacecommerceanalytics = []
nightly-testing = ["clippy", "rusoto_codegen/nightly-testing", "rusoto_credential/nightly-testing"]
opsworks = []
redshift = []
rds = []
route53 = []
route53domains = []
s3 = []
sdb = []
sns = []
sqs = []
ssm = []
storagegateway = []
sts = []
swf = []
unstable = []
waf = []
workspaces = []
packagea = [
	"acm",
	"autoscaling",
	"cloudformation",
	"cloudfront",
	"cloudhsm",
	"cloudsearch",
	"cloudtrail",
	"cloudwatch",
	"codecommit",
	"codedeploy",
	"codepipeline",
	"cognito-identity",
	"config",
	"datapipeline",
	"devicefarm",
	"directconnect",
	"ds",
	"dynamodb",
	"dynamodbstreams",
	"ec2",
	"ecr",
	"ecs",
	"elasticache",
	"elasticbeanstalk",
	"elastictranscoder",
	"elb",
	"elbv2",
	"emr",
	"events",
	"firehose"
]
packageb = [
	"iam",
	"importexport",
	"inspector",
	"iot",
	"kinesis",
	"kms",
	"lambda",
	"logs",
	"machinelearning",
	"marketplacecommerceanalytics",
	"opsworks",
	"redshift",
	"rds",
	"route53",
	"route53domains",
	"s3",
	"sdb",
	"sns",
	"sqs",
	"ssm",
	"storagegateway",
	"swf",
	"waf",
	"workspaces"
]
