[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh", "helpers/**/*", "codegen/**/*"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.22.0"

[build-dependencies]
rustc_version = "0.1.7"
rayon = "0.6.0"

[build-dependencies.rusoto_codegen]
default-features = false
path = "codegen"
version = ">= 0.6.0"

[dependencies]
chrono = "0.2.21"
hyper = "0.10.0"
hyper-native-tls = "0.2.1"
lazy_static = "0.2.1"
log = "0.3.6"
md5 = "0.3.2"
regex = "0.2.1"
ring = "0.6"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
time = "0.1.35"
url = "1.2.0"
xml-rs = "0.3"

[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.rusoto_credential]
path = "credential"
version = "0.4.0"

[dependencies.serde_codegen]
optional = true
version = "0.8.0"

[dependencies.serde_derive]
optional = true
version = "0.8.19"

[dev-dependencies]
env_logger = "0.4.0"
rand = "^0.3.14"

[features]
all = [
		"acm",
		"application-autoscaling",
		"appstream",
	   	"autoscaling",
	   	"budgets",
	   	"cloudformation",
	   	"cloudfront",
	   	"cloudhsm",
	   	"cloudsearch",
	   	"cloudtrail",
	   	"cloudwatch",
	   	"codebuild",
	   	"codecommit",
	   	"codedeploy",
	   	"codepipeline",
	   	"cognito-identity",
	   	"cognito-idp",
	   	"config",
	   	"cur",
	   	"datapipeline",
	   	"devicefarm",
	   	"directconnect",
	   	"discovery",
	   	"dms",
	   	"ds",
	   	"dynamodb",
	   	"dynamodbstreams",
	   	"ec2",
	   	"ecr",
	   	"ecs",
	   	"elasticache",
	   	"elasticbeanstalk",
	   	"elastictranscoder",
	   	"elb",
	   	"elbv2",
	   	"emr",
	   	"events",
	   	"firehose",
	   	"gamelift",
	   	"health",
	   	"iam",
	   	"importexport",
	   	"inspector",
	   	"iot",
	   	"kinesis",
	   	"kinesisanalytics",
	   	"kms",
	   	"lambda",
	   	"lightsail",
	   	"logs",
	   	"machinelearning",
	   	"marketplacecommerceanalytics",
	   	"meteringmarketplace",
	   	"opsworks",
	   	"redshift",
	   	"rds",
	   	"route53",
	   	"route53domains",
	   	"s3",
	   	"sdb",
	   	"sns",
	   	"sqs",
	   	"ssm",
	   	"storagegateway",
	   	"swf",
	   	"waf",
	   	"workspaces"
	]
acm = []
application-autoscaling = []
appstream = []
autoscaling = []
budgets = []
cloudformation = []
cloudfront = []
cloudhsm = []
cloudsearch = []
cloudtrail = []
cloudwatch = []
codecommit = []
codebuild = []
codedeploy = []
codepipeline = []
cognito-identity = []
cognito-idp = []
config = []
cur = []
datapipeline = []
default = ["rusoto_codegen/serde_codegen", "serde_codegen"]
devicefarm = []
directconnect = []
discovery = []
dms = []
ds = []
dynamodb = []
dynamodbstreams = []
ec2 = []
ecr = []
ecs = []
elasticache = []
elasticbeanstalk = []
elastictranscoder = []
elb = []
elbv2 = []
emr = []
events = []
firehose = []
gamelift = []
health = []
iam = []
importexport = []
inspector = []
iot = []
kinesis = []
kinesisanalytics = []
kms = []
lambda = []
lightsail = []
logs = []
machinelearning = []
marketplacecommerceanalytics = []
meteringmarketplace = []
nightly-testing = ["clippy", "rusoto_codegen/nightly-testing", "rusoto_credential/nightly-testing", "unstable"]
opsworks = []
redshift = []
rds = []
route53 = []
route53domains = []
s3 = []
sdb = []
sns = []
sqs = []
ssm = []
storagegateway = []
swf = []
unstable = ["rusoto_codegen/unstable", "rusoto_credential/unstable", "serde_derive"]
waf = []
workspaces = []
