[package]
name = "rusoto"
version = "0.12.1"
authors = ["Anthony DiMarco <anthony.dimarco@dualspark.com>", "Matthew Mayer <matthewkmayer@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["AWS", "Amazon"]
description = "AWS SDK for Rust"
repository = "https://github.com/rusoto/rusoto"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh"]
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
aws_integration = ["dynamodb", "ecs", "kms", "s3", "sqs", "dynamodb"]
ecs = []
s3 = []
sqs = []
dynamodb = []
kms = []

[build-dependencies]
regex = "^0.1.51"
Inflector = "0.2.0"
# for faster development of botocore_parser this can can be set to use a local copy:
# botocore_parser = { path = "../botocore_parser" }
botocore_parser = "^0.1.1"
serde_codegen = { version = "0.6.14", optional = true }
serde_json = "0.6.0"
syntex = "^0.29.0"

[dependencies]
serde = "0.6.15"
serde_json = "0.6.0"
serde_macros = { version = "0.6.14", optional = true }
xml-rs = "^0.1.26"
time = "^0.1.34"
openssl = "^0.7.5"
hyper = "^0.7.2"
url = "^0.2.37"
rustc-serialize = "^0.3.18"
regex = "^0.1.51"
chrono = "^0.2.19"
rust-crypto = "^0.2.34"
log = "^0.3.3"

[dev-dependencies]
env_logger = "^0.3.2"
