[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>"]
build = "build.rs"
description = "AWS SDK for Rust"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.12.1"

[features]
all = ["dynamodb", "ecs", "ets", "kms", "s3", "sqs"]
default = ["with-syntex"]
dynamodb = []
ecs = []
ets = []
kms = []
nightly = ["serde_macros", "rusoto_codegen/nightly"]
nightly-testing = ["clippy", "nightly"]
s3 = []
sqs = []
with-syntex = ["rusoto_codegen/with-syntex"]

[build-dependencies.rusoto_codegen]
default-features = false
path = "codegen"

[dependencies]
chrono = "0.2.21"
hyper = "0.8.1"
log = "0.3.6"
openssl = "0.7.9"
regex = "0.1.65"
rustc-serialize = "0.3.19"
serde = "0.7.0"
serde_json = "0.7.0"
time = "0.1.35"
url = "0.5.9"
xml-rs = "0.1.26"

[dependencies.clippy]
optional = true
version = "0.0.63"

[dependencies.serde_macros]
optional = true
version = "0.7.2"

[dev-dependencies]
env_logger = "0.3.3"
rand = "^0.3.14"
