[package]
name = "rusoto"
version = "0.11.1"
authors = ["Anthony DiMarco <anthony.dimarco@dualspark.com>", "Matthew Mayer <matthewkmayer@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["AWS", "Amazon"]
description = "AWS SDK for Rust"
repository = "https://github.com/rusoto/rusoto"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh"]
build = "build.rs"

[build-dependencies]
serde_codegen = "^0.6.9"
syntex = "^0.26.0"

[dependencies]
xml-rs = "^0.1.26"
time = "^0.1.34"
openssl = "^0.7.1"
hyper = "^0.7.0"
url = "^0.2.37"
rustc-serialize = "^0.3.16"
regex = "^0.1.41"
chrono = "^0.2.17"
rust-crypto = "^0.2.34"
log = "^0.3.3"
serde = "0.6.7"
serde_json = "0.6.0"

[dev-dependencies]
env_logger = "*"

[features]
aws_integration = ["dynamodb", "ecs", "kms", "s3", "sqs", "dynamodb"]
ecs = []
s3 = []
sqs = []
dynamodb = []
kms = []
