[package]
name = "rusoto"
version = "0.7.0"
authors = ["Anthony DiMarco <anthony.dimarco@dualspark.com>", "Matthew Mayer <matthew@dualspark.com>"]
license = "MIT"
readme = "README.md"
keywords = [ "AWS", "SQS", "Amazon", "DynamoDB", "S3" ]
description = "AWS client libraries for Rust"
repository = "https://github.com/DualSpark/rusoto"
documentation = "http://dualspark.github.io/rusoto/rusoto/index.html"

[dependencies]
xml-rs = "=0.1.26"
time = "=0.1.32"
openssl = "=0.6.7"
hyper = "=0.6.15"
url = "=0.2.37"
rustc-serialize = "=0.3.16"
regex = "=0.1.41"
chrono = "=0.2.16"
rust-crypto = "=0.2.31"
