[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>"]
build = "build.rs"
description = "AWS SDK for Rust"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh", "helpers/**/*", "codegen/**/*"]
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.18.1"

[build-dependencies]
rustc_version = "0.1.7"

[build-dependencies.rusoto_codegen]
default-features = false
path = "codegen"
version = ">= 0.2.8"

[dependencies]
chrono = "0.2.21"
hyper = "0.9.10"
lazy_static = "0.2.1"
log = "0.3.6"
md5 = "0.2"
regex = "0.1.65"
ring = "0.4"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
time = "0.1.35"
url = "1.2.0"
xml-rs = "0.1.26"

[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.rusoto_credential]
path = "credential"
version = "0.1.0"

[dependencies.serde_macros]
optional = true
version = "0.8.0"

[dev-dependencies]
env_logger = "0.3.3"
rand = "^0.3.14"

[features]
all = ["acm", "cloudhsm", "cloudtrail", "codecommit", "codedeploy", "codepipeline", "cognito-identity", "config", "datapipeline", "devicefarm", "directconnect", "ds", "dynamodb", "dynamodbstreams", "firehose", "ec2", "ecr", "ecs", "emr", "elastictranscoder", "events", "iam", "inspector", "iot", "kinesis", "kms", "logs", "machinelearning", "marketplacecommerceanalytics", "opsworks", "route53domains", "s3", "sqs", "ssm", "storagegateway", "swf", "waf", "workspaces"]
acm = []
cloudhsm = []
cloudtrail = []
codecommit = []
codedeploy = []
codepipeline = []
cognito-identity = []
config = []
datapipeline = []
devicefarm = []
directconnect = []
default = ["with-syntex"]
ds = []
dynamodb = []
dynamodbstreams = []
ec2 = []
ecr = []
ecs = []
emr = []
elastictranscoder = []
events = []
firehose = []
iam = []
inspector = []
iot = []
kinesis = []
kms = []
logs = []
machinelearning = []
marketplacecommerceanalytics = []
nightly-testing = ["clippy", "unstable"]
opsworks = []
route53domains = []
s3 = []
sqs = []
ssm = []
storagegateway = []
swf = []
unstable = ["serde_macros", "rusoto_codegen/unstable"]
waf = []
with-syntex = ["rusoto_codegen/with-syntex"]
workspaces = []
