doc-valid-idents = [
    "CloudHSM",
    "CloudTrail",
    "CloudWatch",
    "CodeCommit",
    "CodeDeploy",
    "CodePipeline",
    "DynamoDB",
    "IoT",
    "MapReduce",
    "OpsWorks",
    "WorkSpaces",
    "OpenID",
    "OAuth"
]
