[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>", "Nikita Pekin <contact@nikitapek.in>"]
description = "AWS SDK for Rust - Amazon Simple Storage Service @ 2006-03-01"
documentation = "https://rusoto.github.io/rusoto/rusoto_core/index.html"
keywords = ["AWS", "Amazon", "s3"]
license = "MIT"
name = "rusoto_s3"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.30.0"
homepage = "https://www.rusoto.org/"

[build-dependencies]

[dependencies]
base64 = "0.9"
hex = "0.3"
hyper = "0.10.0"
md5 = "0.3.6"
xml-rs = "0.7"

[dependencies.rusoto_core]
version = "0.30.0"
path = "../../core"
[dev-dependencies.rusoto_mock]
version = "0.25.0"
path = "../../../mock"
