[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
description = "AWS SDK for Rust - Request Signing"
documentation = "https://docs.rs/rusoto_signature"
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto_signature"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.43.0-beta1"
homepage = "https://www.rusoto.org/"
edition = "2018"

[badges]
appveyor = { repository = "matthewkmayer/rusoto", branch = "master" }
azure-devops = { project = "matthewkmayer/Rusoto", pipeline = "rusoto.rusoto", build="1" }

[build-dependencies]
rustc_version = "0.2"

[dependencies]
bytes = "0.5"
futures = "0.3"
hmac = "0.7"
http = "0.2"
hyper = "0.13"
log = "0.4.1"
md5 = "0.7"
base64 = "0.11"
hex = "0.4"
serde = "1"
sha2 = "0.8.0"
time = "0.2"
pin-project = "0.4"
percent-encoding = "2"
tokio = { version = "0.2", features = ["macros"] }

[dependencies.rusoto_credential]
path = "../credential"

[dev-dependencies]
serde_json = "1"
serde_test = "1"

