[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>", "Nikita Pekin <contact@nikitapek.in>"]
description = "AWS SDK for Rust - AWS Glue @ 2017-03-31"
documentation = "https://rusoto.github.io/rusoto/rusoto_glue/index.html"
keywords = ["AWS", "Amazon", "glue"]
license = "MIT"
name = "rusoto_glue"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.39.0"
homepage = "https://www.rusoto.org/"
edition = "2018"

[build-dependencies]

[dependencies]
bytes = "0.4.12"
futures = "0.1.16"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"

[dependencies.rusoto_core]
version = "0.39.0"
path = "../../core"
default-features = false
[dev-dependencies.rusoto_mock]
version = "0.39.0"
path = "../../../mock"

[features]
default = ["rusoto_core/default"]
rustls = ["rusoto_core/rustls"]
